name: ci

on:
  pull_request:

jobs:
  nocommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: nobssoftware/nocommit@v3

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: ./.github/actions/setup-node
      - run: |
          npm run format
          test -z "$(git status --porcelain)"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: ./.github/actions/setup-node
      - run: |
          npm run build
