name: cron

on:
  # NOMERGE
  push:
    branches:
      - chore/manual-gen
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/setup-terraform
      - run: npm run start
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: 'chore: update'
